source_if_exists () {
	[[ -f "$1" ]] && source "$1"
}


source_if_exists "$(brew --prefix)/etc/profile.d/bash_completion.sh"
source_if_exists "$XDG_CONFIG_HOME/functions/docker-functions"
source_if_exists "$XDG_CONFIG_HOME/bash/git-completion.bash"
source_if_exists "$XDG_CONFIG_HOME/alias"

# Colors
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
    xterm) color_prompt=yes;;
esac


HISTSIZE=10000
# Save 2,000,000 lines of history to disk (will have to grep ~/.bash_history for full listing)
HISTFILESIZE=2000000
# Append to history instead of overwrite
shopt -s histappend
# Ignore redundant or space commands
HISTCONTROL=ignoreboth
# Ignore more
HISTIGNORE='ls:ll:ls -alh:pwd:clear:history'
# Set time format
HISTTIMEFORMAT='%F %T '
# Multiple commands on one line show up as a single line
shopt -s cmdhist
# Append new history lines, clear the history list, re-read the history list, print prompt.
export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"

# Vi mode
set -o vi

bind '"\e[1;5A":history-search-backward'
bind '"\e[1;5B":history-search-forward'
bind '"\e[1;5C":forward-word'
bind '"\e[1;5D":backward-word'

# Bash Prompt
export PS1="\u@\h:\[\e[32m\]\w\[\e[m\] "

# Load git completition

